[package]
name = "wasm-registry"
version = "0.1.0"
edition = "2021"
resolver = "2"

[features]
default = ["cli", "client", "server"]
cli = ["anyhow", "clap", "tokio", "tokio-util/compat", "tracing-subscriber"]
client = ["reqwest"]
server = ["axum", "axum-macros", "tokio"]

[[bin]]
name = "warg-test-client"
required-features = ["cli", "client"]

[[bin]]
name = "wargd"
required-features = ["cli", "server"]

[dependencies]
anyhow = { version = "1.0", optional = true }
axum = { version = "0.5", features = ["headers"], optional = true }
axum-macros = { version = "0.2", optional = true }
base64 = "0.13"
bytes = "1.1"
clap = { version = "3.2.5", features = ["derive"], optional = true }
ed25519-compact = { version = "1.0", features = ["traits"] }
futures = "0.3"
hex = "0.4"
http = "0.2"
p256 = "0.11"
reqwest = { version = "0.11", features = ["json", "stream"], optional = true }
secrecy = "0.8"
semver = { version = "1.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
signature = "1.5"
thiserror = "1.0"
tokio = { version = "1", features = ["full"], optional = true } # TODO: probably don't need "full"
tokio-util = { version = "0.7", optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"], optional = true }
url = "2"
zeroize = "1.5"